/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/BaseLayout': RouteRecordInfo<'/BaseLayout', '/BaseLayout', Record<never, never>, Record<never, never>>,
    '/BoardList': RouteRecordInfo<'/BoardList', '/BoardList', Record<never, never>, Record<never, never>>,
    '/BoardView': RouteRecordInfo<'/BoardView', '/BoardView', Record<never, never>, Record<never, never>>,
    '/CommentComp': RouteRecordInfo<'/CommentComp', '/CommentComp', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/Menu': RouteRecordInfo<'/Menu', '/Menu', Record<never, never>, Record<never, never>>,
    '/registration': RouteRecordInfo<'/registration', '/registration', Record<never, never>, Record<never, never>>,
  }
}
